### ISSUE TITLE
Incorrect Application data returned from GetApplicationByID

### ISSUE THREAD

**Issue by aarondees-blabs** [alien4cloud/alien4cloud-go-client#17]
Hi,

I noticed today that when using the GetApplicationByID function in the application service the incorrect Application data is returned. It seems that regardless of what application ID is given the same Application data is returned. For example, say I have 2 applications

ID: application1
Name: Application 1

ID: applicaiton2
Name: Application 2

And I want to get 'Application 2' by its ID using;

application, err := GetApplicationByID(ctx , "applicaiton2")

The returned application will hold the information belonging to 'Application 1';

application.ID: "application1"
application.Name: "Application 1"

This seems to be a recent issue as it was working before today.

Thanks,
Aaron

**Comment by aarondees-blabs** [comment]
Hi I've had a look an it seems that the error is coming from the Alien4Cloud /applications/search endpoint, regardless of the ID searched for it will return you the data for the first application.

For example, in below screen shots I have provided projectTest_3 as id to search for and am returned data regarding projectTest
<img width="963" alt="Screenshot 2020-05-20 at 12 56 36" src="https://user-images.githubusercontent.com/60221266/82444558-5252fc00-9a9b-11ea-9841-685ca46c50f8.png">
<img width="959" alt="Screenshot 2020-05-20 at 12 57 03" src="https://user-images.githubusercontent.com/60221266/82444565-554dec80-9a9b-11ea-9b56-73e10dde8dbe.png">

**Comment by laurentganne** [comment]
Yes, seeing that this request `$a4cURL/rest/latest/applications/search` with a `query` parameter doesn't have the behavior we need.
For example querying for `projectTest_3` with `size=10` will return applications `projectTest`, `projectTest_2` and `projectTest_3` (but it won't return application `Abc`, or application `Testxxx`)
It should not be a change in behavior as the A4C version of the first test setup didn't change. 

But found another way to do the request that should correspond to our need:
As we want to get the application for a given ID, there is the REST API call `$a4cURL/rest/latest/applications/<application ID>` that returns the application for a given ID.

For example, this request has the behavior we expect:

```bash
curl --request GET \
 --url  $a4cURL/rest/latest/applications/projectTest_3 \
 --insecure \
 --cookie cookies.a4c 
```

So the code of `GetApplicationByID()` could be changed to use this REST API, instead of doing a search query.
